version: "3.7"

services:
    app:
        build: .
        volumes:
            - .:/app
        container_name: cmp-crawler-app
        restart: always
        expose:
            - "${APP_PORT}"
        ports:
            - "${APP_PORT}:${APP_INTERNAL_PORT}"
        command:
            - sh
            - -c
            - start-node.sh
        env_file: .env
        security_opt:
            - seccomp=./.docker/chrome/chrome.json
        depends_on:
            db:
                condition: service_healthy
        networks:
            - backend

    db:
        image: postgres:14.6
        container_name: cmp-crawler-db
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf:delegated
            - ./var/postgres-data:/var/lib/postgresql/data:cached
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=cmp-crawler
        command:
            - postgres
            - -c
            - "config_file=/etc/postgresql/postgresql.conf"
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - backend

networks:
    backend:
